package api

import (
	"encoding/json"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// ============================================================================
// Named Operation Schema Validation (#886)
// ============================================================================
//
// Every GraphQL document this package sends is checked against the vendored
// public schema. This is the one check that can catch GitHub renaming or
// removing a field: hand-written mocks encode our assumptions about GitHub's
// responses, so they keep passing when the real schema moves. Zero API traffic
// — the capture transport answers every request itself.
//
// How the documents are obtained: most queries are shurcooL struct-based, so
// the document is generated by the library at call time rather than written
// literally, and constructQuery/constructMutation are unexported. So the
// document is captured, not requested — we point the client at a transport that
// records what was sent. Construction and POST both happen before the response
// is unmarshalled, which is why a stub response is enough to harvest a document.

// documentOperationName extracts the operation name from a GraphQL document,
// e.g. "query GetIssue($n:Int!)..." -> "GetIssue". Anonymous documents
// ("query { i0: issue(...) }") have none and yield "".
var documentOperationNamePattern = regexp.MustCompile(`^\s*(?:query|mutation)\s+([A-Za-z_][A-Za-z0-9_]*)`)

func documentOperationName(doc string) string {
	m := documentOperationNamePattern.FindStringSubmatch(doc)
	if m == nil {
		return ""
	}
	return m[1]
}

// capturingTransport records every GraphQL document that reaches the wire and
// answers it locally. Responses default to an empty data object; a per-operation
// response can be supplied for methods that only issue their second call if the
// first one came back with something usable.
type capturingTransport struct {
	mu        sync.Mutex
	docs      []string
	responses map[string]string
}

func (c *capturingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	var payload struct {
		Query string `json:"query"`
	}
	if req.Body != nil {
		body, err := io.ReadAll(req.Body)
		if err != nil {
			return nil, err
		}
		_ = json.Unmarshal(body, &payload)
	}

	if payload.Query != "" {
		c.mu.Lock()
		c.docs = append(c.docs, payload.Query)
		c.mu.Unlock()
	}

	body := `{"data":{}}`
	if r, ok := c.responses[documentOperationName(payload.Query)]; ok {
		body = r
	}
	return makeResp(200, body), nil
}

func (c *capturingTransport) captured() []string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return append([]string(nil), c.docs...)
}

// namedOperationInvocations drives one Client method per named operation.
//
// Arguments only need to be plausible enough to reach the send — return values
// are discarded and errors are expected, since the stub response satisfies no
// method's expectations. What matters is that the document was constructed and
// posted.
func namedOperationInvocations() []func(c *Client) {
	cursor := "Y3Vyc29yOnYyOpHOAA"
	states := []IssueState{IssueStateOpen}

	return []func(c *Client){
		// queries.go
		func(c *Client) { _, _ = c.getUserProject("owner", 1) },
		func(c *Client) { _, _ = c.getOrgProject("owner", 1) },
		func(c *Client) { _, _ = c.fetchProjectFieldByName("PVT_kw1", "Status") },
		func(c *Client) { _, _, _ = c.getProjectFieldsPage("PVT_kw1", &cursor) },
		func(c *Client) { _, _ = c.GetIssue("owner", "repo", 1) },
		func(c *Client) { _, _, _ = c.GetIssueWithProjectFields("PVT_kw1", "owner", "repo", 1) },
		func(c *Client) { _, _ = c.GetProjectItemIDForIssue("PVT_kw1", "owner", "repo", 1) },
		func(c *Client) { _, _, _ = c.getProjectItemsPage("PVT_kw1", &cursor) },
		func(c *Client) { _, _, _ = c.getMinimalProjectItemsPage("PVT_kw1", &cursor) },
		func(c *Client) { _, _, _ = c.getBoardItemsPage("PVT_kw1", &cursor) },
		func(c *Client) { _, _ = c.GetSubIssues("owner", "repo", 1) },
		func(c *Client) { _, _, _ = c.getRepositoryIssuesPage("owner", "repo", states, &cursor) },
		func(c *Client) { _, _, _ = c.searchIssuesPage("repo:o/r is:issue", 50, &cursor) },
		func(c *Client) { _, _ = c.GetOpenIssuesByLabels("owner", "repo", []string{"bug"}) },
		func(c *Client) { _, _, _ = c.getIssuesByLabelPage("owner", "repo", "bug", states, &cursor) },
		func(c *Client) { _, _ = c.GetParentIssue("owner", "repo", 1) },
		func(c *Client) { _, _ = c.listUserProjects("owner") },
		func(c *Client) { _, _ = c.listOrgProjects("owner") },
		func(c *Client) { _, _ = c.GetIssueComments("owner", "repo", 1) },
		func(c *Client) { _, _ = c.ListLabels("owner", "repo") },
		func(c *Client) { _, _ = c.GetLabel("owner", "repo", "bug") },

		// mutations.go
		func(c *Client) { _, _ = c.CreateIssue("owner", "repo", "title", "body", nil) },
		func(c *Client) { _, _ = c.GetRepositoryID("owner", "repo") },
		func(c *Client) { _ = c.AddSubIssue("I_parent", "I_child") },
		func(c *Client) { _ = c.RemoveSubIssue("I_parent", "I_child") },
		func(c *Client) { _, _ = c.GetOwnerID("owner") },
		func(c *Client) { _ = c.AddLabelToIssue("owner", "repo", "I_kw1", "bug") },
		func(c *Client) { _ = c.RemoveLabelFromIssue("owner", "repo", "I_kw1", "bug") },
		func(c *Client) { _, _ = c.getLabelID("owner", "repo", "bug") },
		func(c *Client) { _, _ = c.getMilestoneID("owner", "repo", "v1.0") },
		func(c *Client) { _, _, _ = c.GetProjectItemFieldValue("PVT_kw1", "PVTI_1", "Status") },
		func(c *Client) { _, _ = c.GetAuthenticatedUser() },
		func(c *Client) { _ = c.CreateLabel("owner", "repo", "bug", "d73a4a", "desc") },
		func(c *Client) { _, _ = c.AddIssueComment("I_kw1", "body") },
		func(c *Client) { _ = c.CloseIssue("I_kw1", "COMPLETED") },
		func(c *Client) { _ = c.ReopenIssue("I_kw1") },
		func(c *Client) { _ = c.UpdateIssueBody("I_kw1", "body") },
		func(c *Client) { _ = c.DeleteLabel("owner", "repo", "bug") },
		func(c *Client) { _ = c.UpdateLabel("owner", "repo", "bug", "bug2", "d73a4a", "desc") },
	}
}

// captureNamedOperationDocuments drives every invocation and returns the
// documents that reached the wire, keyed by operation name.
func captureNamedOperationDocuments(t *testing.T) map[string]string {
	t.Helper()

	transport := &capturingTransport{responses: namedOperationResponses()}
	SetTestTransport(transport)
	defer SetTestTransport(nil)
	SetTestAuthToken("test-token") // go-gh refuses to construct a client without one (CI lacks gh auth)
	defer SetTestAuthToken("")

	c, err := NewClient()
	if err != nil {
		t.Fatalf("NewClient failed: %v", err)
	}

	for _, invoke := range namedOperationInvocations() {
		invoke(c) // errors expected and ignored — only the sent document matters
	}

	docs := make(map[string]string)
	for _, d := range transport.captured() {
		if name := documentOperationName(d); name != "" {
			docs[name] = d
		}
	}
	return docs
}

// namedOperationResponses supplies canned responses for the operations whose
// callers chain a second request off the first one's result.
//
// Only one is needed. 36 of the 40 operations are harvested from an empty
// response, because the document is already on the wire by the time the reply is
// unmarshalled. The exceptions are the four label mutations: each resolves the
// label's node id first and bails with "label %q not found" on an empty result,
// so their own document never gets sent. Giving GetLabelID an id lets all four
// through.
func namedOperationResponses() map[string]string {
	return map[string]string{
		"GetLabelID": `{"data":{"repository":{"label":{"id":"LA_kwDOTestLabel"}}}}`,
	}
}

// knownInvalidOperations lists operations that do not validate against the
// vendored schema because the query itself is wrong, mapped to the issue
// tracking the fix.
//
// This is a quarantine, not an exemption. TestNamedOperations_KnownInvalidStillFail
// asserts each entry STILL fails, so fixing the underlying bug turns that test
// red until the entry is removed. A quarantine that silently rots is worse than
// no quarantine — it reads as coverage while providing none.
var knownInvalidOperations = map[string]string{
	"GetProjectItemFieldValue": "#888 — selects name directly on the ProjectV2FieldConfiguration union; needs an inline fragment on ProjectV2FieldCommon",
}

// loadVendoredSchema parses the vendored schema once per test.
func loadVendoredSchema(t *testing.T) *ast.Schema {
	t.Helper()
	raw, err := os.ReadFile(vendoredSchemaPath)
	if err != nil {
		t.Fatalf("vendored schema not found at %s: %v", vendoredSchemaPath, err)
	}
	schema, gerr := gqlparser.LoadSchema(&ast.Source{Name: "github.docs", Input: string(raw)})
	if gerr != nil {
		t.Fatalf("vendored schema failed to parse: %v", gerr)
	}
	return schema
}

// sourceEnumeratedOperations lists the operation names this package sends, read
// from the production sources. Test files are excluded deliberately: they define
// operations of their own (Test, Viewer in client_test.go) that GitHub's schema
// knows nothing about.
func sourceEnumeratedOperations(t *testing.T) []string {
	t.Helper()

	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("cannot read package dir: %v", err)
	}

	pattern := regexp.MustCompile(`gql\.(?:Query|Mutate)\("([A-Za-z]+)"`)
	seen := make(map[string]bool)
	for _, e := range entries {
		name := e.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		src, err := os.ReadFile(name)
		if err != nil {
			t.Fatalf("cannot read %s: %v", name, err)
		}
		for _, m := range pattern.FindAllStringSubmatch(string(src), -1) {
			seen[m[1]] = true
		}
	}

	ops := make([]string, 0, len(seen))
	for op := range seen {
		ops = append(ops, op)
	}
	sort.Strings(ops)
	return ops
}

// TestNamedOperations_ValidateAgainstVendoredSchema is the check that catches an
// upstream field rename or removal.
func TestNamedOperations_ValidateAgainstVendoredSchema(t *testing.T) {
	schema := loadVendoredSchema(t)
	docs := captureNamedOperationDocuments(t)

	if len(docs) == 0 {
		t.Fatal("no documents captured — the capture transport is not wired up")
	}

	names := make([]string, 0, len(docs))
	for name := range docs {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		if _, quarantined := knownInvalidOperations[name]; quarantined {
			continue // asserted separately by TestNamedOperations_KnownInvalidStillFail
		}
		t.Run(name, func(t *testing.T) {
			if _, errs := gqlparser.LoadQueryWithRules(schema, docs[name], nil); len(errs) > 0 {
				for _, e := range errs {
					t.Errorf("%s does not validate against the vendored schema: %s", name, e.Message)
				}
				t.Logf("document: %s", docs[name])
			}
		})
	}
}

// TestNamedOperations_KnownInvalidStillFail keeps the quarantine honest. Every
// entry must still be broken; the moment one starts validating, the entry is
// stale and has to go, or the operation silently drops out of coverage.
func TestNamedOperations_KnownInvalidStillFail(t *testing.T) {
	schema := loadVendoredSchema(t)
	docs := captureNamedOperationDocuments(t)

	for name, reason := range knownInvalidOperations {
		doc, ok := docs[name]
		if !ok {
			t.Errorf("%s is quarantined (%s) but no invocation drives it — remove the entry or add the invocation",
				name, reason)
			continue
		}
		if _, errs := gqlparser.LoadQueryWithRules(schema, doc, nil); len(errs) == 0 {
			t.Errorf("%s is quarantined (%s) but now validates cleanly — remove it from knownInvalidOperations",
				name, reason)
		}
	}
}

// ============================================================================
// Anonymous Runtime-Built Document Validation (#886)
// ============================================================================
//
// Eight documents are assembled with fmt.Sprintf at call time instead of being
// generated from a struct, so they carry no operation name and never appear in
// the named-operation enumeration above. They still reach GitHub, so they still
// need checking. All eight travel through the RawGraphQLDoer seam, which
// NewClientWithOptions wires to the same transport as the typed client — so the
// capture rig needs nothing extra.
//
// mutation BatchUpdate is included here rather than above: it IS named, but it
// is Sprintf-built and dispatched via doRawGraphQLBody, so gql.Mutate never sees
// it and the source enumeration cannot find it. It would otherwise fall through
// the gap between the two tests.

// rawDocumentInvocations drives each method that assembles a document by hand.
func rawDocumentInvocations() []struct {
	label  string
	invoke func(c *Client)
} {
	refs := []IssueRef{{Owner: "owner", Repo: "repo", Number: 1}}
	numbers := []int{1, 2}
	fields := []ProjectField{{ID: "PVTF_notes", Name: "Notes", DataType: "TEXT"}}
	updates := []FieldUpdate{{ItemID: "PVTI_1", FieldName: "Notes", Value: "hello"}}

	return []struct {
		label  string
		invoke func(c *Client)
	}{
		{"GetProjectItemsByIssues", func(c *Client) { _, _ = c.GetProjectItemsByIssues("PVT_kw1", refs) }},
		{"GetSubIssueCounts", func(c *Client) { _, _ = c.GetSubIssueCounts("owner", "repo", numbers) }},
		{"GetSubIssuesBatch", func(c *Client) { _, _ = c.GetSubIssuesBatch("owner", "repo", numbers) }},
		{"getProjectFieldsForIssuesBatch", func(c *Client) {
			_, _ = c.getProjectFieldsForIssuesBatch("PVT_kw1", []string{"I_kw1", "I_kw2"})
		}},
		{"GetIssuesWithProjectFieldsBatch", func(c *Client) {
			_, _, _, _ = c.GetIssuesWithProjectFieldsBatch("PVT_kw1", "owner", "repo", numbers)
		}},
		{"GetParentIssueBatch", func(c *Client) { _, _ = c.GetParentIssueBatch("owner", "repo", numbers) }},
		{"getLabelIDs", func(c *Client) { _, _ = c.getLabelIDs("owner", "repo", []string{"bug", "help wanted"}) }},
		{"BatchUpdateProjectItemFields", func(c *Client) {
			_, _ = c.BatchUpdateProjectItemFields("PVT_kw1", updates, fields)
		}},
	}
}

// TestRawDocuments_ValidateAgainstVendoredSchema checks the hand-assembled
// documents. Each builder is driven separately so a failure names the builder
// rather than a line of generated GraphQL.
func TestRawDocuments_ValidateAgainstVendoredSchema(t *testing.T) {
	schema := loadVendoredSchema(t)

	for _, tc := range rawDocumentInvocations() {
		t.Run(tc.label, func(t *testing.T) {
			transport := &capturingTransport{responses: namedOperationResponses()}
			SetTestTransport(transport)
			defer SetTestTransport(nil)
			SetTestAuthToken("test-token") // go-gh refuses to construct a client without one (CI lacks gh auth)
			defer SetTestAuthToken("")

			c, err := NewClient()
			if err != nil {
				t.Fatalf("NewClient failed: %v", err)
			}

			tc.invoke(c) // errors expected and ignored — only the sent document matters

			docs := transport.captured()
			if len(docs) == 0 {
				t.Fatalf("%s sent no document — the invocation does not reach the send", tc.label)
			}

			for _, doc := range docs {
				if _, errs := gqlparser.LoadQueryWithRules(schema, doc, nil); len(errs) > 0 {
					for _, e := range errs {
						t.Errorf("%s does not validate against the vendored schema: %s", tc.label, e.Message)
					}
					t.Logf("document: %s", doc)
				}
			}
		})
	}
}

// TestSchemaValidation_NoLiveAPITraffic asserts the claim the rest of this file
// depends on: nothing here talks to GitHub. Live API calls are barred outright
// (#876 — burst traffic from CI tripped abuse detection and locked the account),
// so "we use a mock" has to be checked rather than believed.
func TestSchemaValidation_NoLiveAPITraffic(t *testing.T) {
	transport := &capturingTransport{responses: namedOperationResponses()}
	SetTestTransport(transport)
	defer SetTestTransport(nil)
	SetTestAuthToken("test-token") // go-gh refuses to construct a client without one (CI lacks gh auth)
	defer SetTestAuthToken("")

	c, err := NewClient()
	if err != nil {
		t.Fatalf("NewClient failed: %v", err)
	}

	// A sentinel only the capture transport can produce: no live endpoint would
	// return this id for label "bug" on owner/repo. If SetTestTransport failed to
	// take effect, this call would reach GitHub and could not return it.
	got, err := c.getLabelID("owner", "repo", "bug")
	if err != nil {
		t.Fatalf("getLabelID returned an error, so the transport did not answer it: %v", err)
	}
	if got != "LA_kwDOTestLabel" {
		t.Errorf("getLabelID returned %q, not the canned fixture id — the response did not come from the capture transport", got)
	}

	if len(transport.captured()) == 0 {
		t.Fatal("capture transport received no requests — traffic escaped the test transport")
	}

	// The schema oracle is a file on disk, not a network fetch.
	if _, err := os.Stat(vendoredSchemaPath); err != nil {
		t.Errorf("validation must run against the vendored file, but it is not readable: %v", err)
	}
}

// ============================================================================
// Fail-Proof (#886)
// ============================================================================
//
// A validator that cannot fail is worse than no validator: it reports safety it
// is not providing. These tests take a real captured document, inject a field
// GitHub does not have, and require the rejection — with a control asserting the
// same document passes untouched, so the failure is provably caused by the
// injection rather than by a document that was already broken.

const bogusField = "bogusFieldThatDoesNotExist"

// validationErrors returns the validation messages for doc against schema, or
// nil when it validates cleanly.
func validationErrors(schema *ast.Schema, doc string) []string {
	_, gerrs := gqlparser.LoadQueryWithRules(schema, doc, nil)
	var out []string
	for _, e := range gerrs {
		out = append(out, e.Message)
	}
	return out
}

// injectBogusField splices a nonexistent field into a document's first
// selection set after marker.
func injectBogusField(t *testing.T, doc, marker string) string {
	t.Helper()
	i := strings.Index(doc, marker)
	if i < 0 {
		t.Fatalf("marker %q not found in document — the query shape changed and this test needs updating.\ndocument: %s",
			marker, doc)
	}
	cut := i + len(marker)
	return doc[:cut] + bogusField + "," + doc[cut:]
}

func TestFailProof_BogusFieldInNamedOperationIsRejected(t *testing.T) {
	schema := loadVendoredSchema(t)
	docs := captureNamedOperationDocuments(t)

	doc, ok := docs["GetIssue"]
	if !ok {
		t.Fatal("GetIssue was not captured — cannot prove the validator fails")
	}

	// Control: the real document must pass, or the negative below proves nothing.
	if errs := validationErrors(schema, doc); len(errs) > 0 {
		t.Fatalf("control failed: the real GetIssue document does not validate: %v", errs)
	}

	mutated := injectBogusField(t, doc, "issue(number: $number){")

	errs := validationErrors(schema, mutated)
	if len(errs) == 0 {
		t.Fatalf("injecting %q into GetIssue did not fail validation — the validator is not checking fields.\ndocument: %s",
			bogusField, mutated)
	}
	if !strings.Contains(strings.Join(errs, " "), bogusField) {
		t.Errorf("validation failed, but not because of the injected field. Errors: %v", errs)
	}
}

func TestFailProof_BogusFieldInRawDocumentIsRejected(t *testing.T) {
	schema := loadVendoredSchema(t)

	transport := &capturingTransport{responses: namedOperationResponses()}
	SetTestTransport(transport)
	defer SetTestTransport(nil)
	SetTestAuthToken("test-token") // go-gh refuses to construct a client without one (CI lacks gh auth)
	defer SetTestAuthToken("")

	c, err := NewClient()
	if err != nil {
		t.Fatalf("NewClient failed: %v", err)
	}
	_, _ = c.GetSubIssueCounts("owner", "repo", []int{1})

	docs := transport.captured()
	if len(docs) == 0 {
		t.Fatal("GetSubIssueCounts sent no document — cannot prove the validator fails")
	}
	doc := docs[0]

	// Control: the real document must pass.
	if errs := validationErrors(schema, doc); len(errs) > 0 {
		t.Fatalf("control failed: the real raw document does not validate: %v", errs)
	}

	mutated := injectBogusField(t, doc, "subIssues { ")

	errs := validationErrors(schema, mutated)
	if len(errs) == 0 {
		t.Fatalf("injecting %q into a raw document did not fail validation.\ndocument: %s", bogusField, mutated)
	}
	if !strings.Contains(strings.Join(errs, " "), bogusField) {
		t.Errorf("validation failed, but not because of the injected field. Errors: %v", errs)
	}
}

// TestNamedOperations_CoverageIsComplete fails when an operation exists in the
// sources but no invocation drives it. Without this the validation test above
// silently shrinks as operations are added.
func TestNamedOperations_CoverageIsComplete(t *testing.T) {
	docs := captureNamedOperationDocuments(t)

	var uncovered []string
	for _, op := range sourceEnumeratedOperations(t) {
		if _, ok := docs[op]; !ok {
			uncovered = append(uncovered, op)
		}
	}

	if len(uncovered) > 0 {
		t.Errorf("%d operation(s) exist in source but no invocation drives them: %s\n"+
			"Add an entry to namedOperationInvocations (and a response to namedOperationResponses if the caller chains off a first result).",
			len(uncovered), strings.Join(uncovered, ", "))
	}
}
